### ISSUE TITLE
Removing a dependency doesn't trigger lock

### ISSUE THREAD

**Issue by blakeNaccarato** [blakeNaccarato/copier-python#397]
### To-do

- [ ] Write a changelog entry

### Please check that this bug hasn't been reported before

- [X] I searched [here](https://github.com/blakeNaccarato/copier-python/issues?q=label%3Abug+sort%3Acomments-desc) or [here](https://github.com/search?q=repo%3AblakeNaccarato/copier-python+label%3Abug&type=issues) and couldn't find a similar issue.

### Please confirm that this bug affects the latest version

- [X] This bug affects version `0.0.0` of `copier_python`.

### Please indicate which operating system(s) you are using

- [X] Linux
- [X] macOS
- [X] Windows

### Expected behavior

Removing a dependency should trigger a lock.

### Current behaviour

It doesn't. Probably because we're only checking that all direct dependencies are in the lock.

### Steps to reproduce

Remove any direct dependency and sync. The lock won't be triggered.

### Possible solution

Also check that all direct dependencies in the lock are still direct dependencies, as well as with submodules.

**Comment by blakeNaccarato** [comment]
Fixed in https://github.com/blakeNaccarato/copier-python/commit/1dc630c8b21dd35f02289dc14c77bfe01e2cd3f9, need to attach a changelog entry to this.
