### ISSUE TITLE
Cache `uv` in allowable folder (not `..`), but don't break Codecov flow

### ISSUE THREAD

**Issue by blakeNaccarato** [blakeNaccarato/copier-python#451]
### Please use this form appropriately

- [X] I am a maintainer or I have been directed to use this form.

### Please check that this internal matter hasn't already been raised

- [X] I searched [here](https://github.com/blakeNaccarato/copier-python/issues?q=label%3Ainternal+sort%3Acomments-desc) or [here](https://github.com/search?q=repo%3AblakeNaccarato/copier-python+label%3Ainternal&type=issues) and couldn't find a similar issue.

### Tasks

- [ ] Apply [this fix from `boilercv`](https://github.com/softboiler/boilercv/blob/24fd813414a28f296c2147abec89305b77c9efa7/.github/workflows/ci.yml#L190-L195)

### Description

Need to fix caching in a way that doesn't break Codecov.
